### ISSUE TITLE
Module Error (Problem Solved)

### ISSUE THREAD

**Issue by passionyang16** [whoareyouwhoami/ProjectCasa#1]
collects.py
- Error:
import Webcrawling.decorators as dc
ModuleNotFoundError: No module named 'Webcrawling'
- Fixed:
import decorators as dc

run_test.py
- Error:
import Webcrawling.collect as WebCrawl
ModuleNotFoundError: No module named 'Webcrawling'
- Fixed:
import collect as WebCrawl

**Comment by whoareyouwhoami** [comment]
고쳤습니다~
