### ISSUE TITLE
EDA에 대한 질문입니다.

### ISSUE THREAD

**Issue by traceofpassion** [whoareyouwhoami/ProjectCasa#29]
@whdbfla6 
실거래가를 자치구별로 나타내고, 이상치를 제거하는 과정을 담으셨는데, EDA를 위한 과정인 것인가요? 아니면 이상치 제거 또한 모델에 반영해야할까요?

**Comment by whdbfla6** [comment]
이상치의 값이 해당 아파트의 단일한 거래정보인 경우에 제외를 하지 않았고, 모델링에도 반영하는게 좋을거 같습니다.

**Comment by traceofpassion** [comment]
데이터 유실 문제 때문에 살리는 게 어떠할 지 제안드립니다.

**Comment by whdbfla6** [comment]
이상치의 값이 해당 아파트의 유일한 가격정보인 경우에 제거를 하지 않고 냅두었습니다. 클러스터링을 진행할 때 가격정보를 변수로 집어넣는다면, 이상치를 제거하는것도 괜찮을거같아요! 데이터 유실이 걱정되신다면 이상치를 포함해서 진행하시고, EDA만 반영하겠습니다.

**Comment by traceofpassion** [comment]
현재도 8000개 아파트 중에 3000개 가량이 비어있는 상태라 데이터 제거에 우려가 있습니다. 가격 정보를 변수로 집어넣을 때 역대 최고가를 고려해서 집어넣을 예정이라 이상치에는 크게 영향을 받지 않을 것으로 보입니다.
