### ISSUE TITLE
EDA 학교 이름에 대한 질문입니다.

### ISSUE THREAD

**Issue by traceofpassion** [whoareyouwhoami/ProjectCasa#30]
@whdbfla6 
538개의 학교가 있으며, 초등학교 데이터만 존재 > 고등학교에 대한 데이터가 아니기 때문에 학교 이름에 따른 실거래가 영향은 없을 것으로 보임 > 제거

이렇게 되어있는데, 혹시 아까 말씀드린 준공사의 방법론과 동일하게 적용이 가능할까요?

**Comment by whdbfla6** [comment]
네 알겠습니다!

**Comment by traceofpassion** [comment]
네 감사합니다:)
